trigger: none

pr:
  branches:
    include:
      - '*'

stages:
  - stage: CI_Checks
    jobs:
      - job:
        displayName: print statement
        pool:
          vmImage: 'ubuntu-latest'
    steps:
    displayName: 'Hello World'
    script: echo "Hello World"

# Testing to see if it triggers a new pipeline build
